---
title: A nf-core Quarto notebook
author: Name Surname
date: last-modified
format:
    nf-core-html: default
---

# A section with a plot

```{r}
#| warning: false
library("ggplot2")
library("palmerpenguins")
data(penguins)
ggplot(penguins, aes(x      = bill_length_mm,
                     y      = bill_depth_mm,
                     colour = species)) +
    geom_point() +
    labs(colour = 'Species') +
    scale_colour_manual(values = c('#24B064', '#3073AF', '#E0191A')) +
    theme_bw()
```

## A subsection with a table

Some text with `inline code` and a
[link](https://quarto.org/docs/output-formats/html-basics.html).

```{r}
#| tbl-cap: A table
penguins[1:20, ]
```

# Colours

If you want to write something with _e.g._ the [nf-core green]{.green} you can
use `[text to colour]{.green}`. Other available colours are [blue]{.blue},
[red]{.red}, [yellow]{.yellow} and [grey]{.grey}. The hex values for these
colours are `#24B064`, `#3073AF`, `#E0191A`, `#DABC25` and `#B2B2B2`,
respectively.

# Font

The font used is the [Maven Pro Google
font](https://fonts.google.com/specimen/Maven+Pro), as per the [nf-core graphic
design guidelines](https://nf-co.re/docs/contributing/design_guidelines).
